version: "3"

networks:
  tpp-net:

volumes:
  redis-data:

services:
  redis:
    image: redis:5.0.6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - tpp-net
