spring:
  application.name: oauth-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: @project.version@
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8082

oauth:
  server:
    url:
  get-token-endpoint:
    enabled: false
  refresh-token-implicitly:
    enabled: true
    seconds-before-expiration: 60
  redirect:
    success-url:
    error-url:
  bank-config:
    adorsys:
      clientId:
    commerzbank:
      clientId:
    comdirect:
      clientId:
    ing:
      clientId:

xs2a-adapter:
  url:

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: full

---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379

xs2a-adapter:
  url: http://localhost:8999

oauth:
  server:
    url: http://localhost:8082
  get-token-endpoint:
    enabled: true
  refresh-token-implicitly:
    enabled: true
    seconds-before-expiration: 60
  redirect:
    success-url: /success
    error-url: /error
  bank-config:
    adorsys:
      clientId: ADORSYS_CLIENT_ID
    commerzbank:
      clientId: VALID_CLIENT_ID
    comdirect:
      clientId: VALID_CLIENT_ID
    ing:
      clientId:

logging:
  level:
    de.adorsys: DEBUG
