spring:
  application.name: oauth-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: @project.version@
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8082

oauth:
  redirect:
    success-url:
    error-url:

xs2a-adapter:
  url:

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: full

---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379